Dsa ciphers
tomato42/tlslite-ng pull request #418
Opened 2020-07-20 10:45 UTC by Stonemason5040

2020-07-21 10:05 UTC, tomato42 commented
I'm guessing this is a first draft? For one, I think it will need to add also `dheDsaSuites` list, similar to `ecdheEcdsaSuites`

2020-07-22 11:34 UTC, Stonemason5040 commented
> I'm guessing this is a first draft? For one, I think it will need to add also `dheDsaSuites` list, similar to `ecdheEcdsaSuites`

Yeah it is, i will add the `dheDsaSuites` later on.

2020-08-04 11:16 UTC, Stonemason5040 commented
___
*[tlslite/utils/python_dsakey.py, line 6 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MDURVs63Re0BJUahNiZ:-MDtA_6JBudQDdwoXLUc:b-79amvp) ([raw file](https://github.com/tomato42/tlslite-ng/blob/95e9881fe8a6ec161841b6f39f00f4ffe27b8429/tlslite/utils/python_dsakey.py#L6)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

PQG are standard names for the parameters (p for prime, g for generator and q as one letter after p, as the other prime), but I haven't seen "a" and "A" used... where did you find them? (I'd suggest using names used in NIST documentation, as they're the authoritative source on DSA)
</blockquote></details>

It was from Introduction to cryptography from J.A. Buchmann


<!-- Sent from Reviewable.io -->

2020-08-04 11:25 UTC, Stonemason5040 commented
___
*[tlslite/utils/python_dsakey.py, line 55 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MDUSUuJBgpAs8FuUbDc:-MDtBubv-07v8DFJIcDg:b-5fauty) ([raw file](https://github.com/tomato42/tlslite-ng/blob/95e9881fe8a6ec161841b6f39f00f4ffe27b8429/tlslite/utils/python_dsakey.py#L55)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

`k ** -1` I'm pretty sure this won't work, I think you're looking for `invMod(k, self.q)` from cryptomath
</blockquote></details>

Before i use the mod i need to multiply the  `k^-1` by `(bytesToNumber(hashBytes) + self.private_key * r)`


<!-- Sent from Reviewable.io -->

2020-08-04 12:23 UTC, Stonemason5040 commented
___
*[tlslite/utils/python_dsakey.py, line 6 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MDURVs63Re0BJUahNiZ:-MDtPspb-XS9x4tNbHZx:b-3ug34t) ([raw file](https://github.com/tomato42/tlslite-ng/blob/95e9881fe8a6ec161841b6f39f00f4ffe27b8429/tlslite/utils/python_dsakey.py#L6)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

so NIST uses `x`, and `y`?
</blockquote></details>

yes, as described in `FIPS PUB 186-4`


<!-- Sent from Reviewable.io -->

2020-08-04 12:24 UTC, Stonemason5040 commented
___
*[tlslite/utils/dsakey.py, line 11 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MDUPwpsB0osWYcjz9QC:-MDtQRTX5cLn-bkbLzkB:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/95e9881fe8a6ec161841b6f39f00f4ffe27b8429/tlslite/utils/dsakey.py#L11)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

*DSA
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-04 12:24 UTC, Stonemason5040 commented
___
*[tlslite/utils/dsakey.py, line 9 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MDUPvp79zD6sN5u9McD:-MDtQV8hBuEpJoBhFyS_:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/95e9881fe8a6ec161841b6f39f00f4ffe27b8429/tlslite/utils/dsakey.py#L9)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

*DSA
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-04 12:24 UTC, Stonemason5040 commented
___
*[tlslite/utils/dsakey.py, line 12 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MDUPyt17tab14fweFhT:-MDtQZIOAb_lgk45B_aN:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/95e9881fe8a6ec161841b6f39f00f4ffe27b8429/tlslite/utils/dsakey.py#L12)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

*python_dsakey and *PythonDSAKey
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-04 12:24 UTC, Stonemason5040 commented
___
*[tlslite/utils/dsakey.py, line 16 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MDUQ1KE6JztHWaiOPEv:-MDtQbcV-mYb3KzqiVRj:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/95e9881fe8a6ec161841b6f39f00f4ffe27b8429/tlslite/utils/dsakey.py#L16)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

*DSA
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-17 17:50 UTC, Stonemason5040 commented
___
*[tlslite/utils/python_dsakey.py, line 54 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MDu_5RgEh1VzVCH9f4U:-MExXo7y66JGHlD6OLy_:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/080542cc2d68f3ee2445db06e177aaaa049aaa0c/tlslite/utils/python_dsakey.py#L54)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

Are you sure it's the correct way to encode them? Shouldn't they be put into an ASN.1 SEQUENCE? or at the very least, into constant length bytearrays?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-17 17:54 UTC, Stonemason5040 commented
___
*[tlslite/utils/python_dsakey.py, line 52 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MDuZf10Dd2tk3ovw4-V:-MExYejb3rlD3HfNyNGb:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/080542cc2d68f3ee2445db06e177aaaa049aaa0c/tlslite/utils/python_dsakey.py#L52)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

`powMod` result is an integer, no need to cast it again
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-24 11:55 UTC, tomato42 requested changes
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @Stonemason5040)

*[a discussion](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVExJr5Ojc82zVX1Hc:-MFVExJsDp0UueeT5KMD:b-a6zf7t) (no related file):*
You'll need to rebase and drop the Ivan's patch

---
___
*[tlslite/utils/keyfactory.py, line 252 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVFY8l7T1mhLKoTGcU:-MFVFY8l7T1mhLKoTGcV:bgnfz0v) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf698cb8b4f7e2e095a2bca2fe0af91e0154c80b/tlslite/utils/keyfactory.py#L252)):*
> ```Python
>     :param g: domain parameter, generator of q-order cyclic group GP(p)
>     :type y: int
>     :param g: public key
> ```

typo?, shouldn't it be `param y`?
___
*[tlslite/utils/python_dsakey.py, line 37 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVG6PGD7auLLhM5e4W:-MFVG6PGD7auLLhM5e4X:b-vqmopv) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf698cb8b4f7e2e095a2bca2fe0af91e0154c80b/tlslite/utils/python_dsakey.py#L37)):*
> ```Python
>     @staticmethod
>     def generate(L, N):
>         assert (L, N) in [(1024, 160), (2048, 224), (2048, 256), (3072, 256)]
> ```

technically, those are the only valid parameters if we want to be FIPS compliant, but for generation it's probably fine to limit to just those
___
*[tlslite/utils/python_dsakey.py, line 85 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVIzkeDjygTeTODHYO:-MFVIzkeDjygTeTODHYP:byro8em) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf698cb8b4f7e2e095a2bca2fe0af91e0154c80b/tlslite/utils/python_dsakey.py#L85)):*
> ```Python
> 
>         # get r, s keys
>         body, rest = remove_sequence(signature)
> ```

we should verify that rest here is empty, it would be an invalid signature otherwise
___
*[tlslite/utils/python_dsakey.py, line 87 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVIpo_6BrPmLgpt4Pt:-MFVIpoa0RvxIrzMlI70:b1dbfma) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf698cb8b4f7e2e095a2bca2fe0af91e0154c80b/tlslite/utils/python_dsakey.py#L87)):*
> ```Python
>         body, rest = remove_sequence(signature)
>         r, rest = remove_integer(body)
>         s, rest = remove_integer(rest)
> ```

we should verify that rest is empty, it would be an invalid signature otherwise
___
*[tlslite/utils/python_dsakey.py, line 88 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVImC14C5QGTvbrHxw:-MFVImC14C5QGTvbrHxx:b8bqqdz) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf698cb8b4f7e2e095a2bca2fe0af91e0154c80b/tlslite/utils/python_dsakey.py#L88)):*
> ```Python
>         r, rest = remove_integer(body)
>         s, rest = remove_integer(rest)
>         
> ```

nit: whitespace
___
*[tlslite/utils/python_dsakey.py, line 94 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVJ9TV-lsx_0unBxz4:-MFVJ9TV-lsx_0unBxz5:b-64g3b8) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf698cb8b4f7e2e095a2bca2fe0af91e0154c80b/tlslite/utils/python_dsakey.py#L94)):*
> ```Python
>             u1 = (digest * w) % self.q
>             u2 = (r * w) % self.q
>             v = ((powMod(self.g, u1, self.p) * powMod(self.public_key, u2, self.p)) % mpz(self.p)) % mpz(self.q)
> ```

shouldn't `self.p` and `self.q` already be mpz's?


<!-- Sent from Reviewable.io -->

2020-08-25 11:42 UTC, tomato42 requested changes
> Reviewed 4 of 10 files at r7, 7 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: all files reviewed, 8 unresolved discussions (waiting on @Stonemason5040)

___
*[tlslite/x509.py, line 137 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_PiTM0qnB2gH768jY:-MF_PiTM0qnB2gH768jZ:bpdcen5) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/tlslite/x509.py#L137)):*
> ```Python
>             return
>         elif self.certAlg == "dsa":
>             self._ecdsa_pubkey_parsing(
> ```

`_ecdsa_pubkey_parsing`?
___
*[tlslite/x509.py, line 198 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_Q6WV6JtQIUxDGuJn:-MF_Q6WV6JtQIUxDGuJo:b-6sm6a6) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/tlslite/x509.py#L198)):*
> ```Python
>         self.publicKey = _create_public_ecdsa_key(x, y, curve_name)
> 
>     def _dsa_pubkey_parsing(self, subject_public_key_info):
> ```

test case with a X.509 certificate?
___
*[tlslite/utils/python_dsakey.py, line 94 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVJ9TV-lsx_0unBxz4:-MF_OPJjBwzg1YMIOcmC:bgu9cbn) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf698cb8b4f7e2e095a2bca2fe0af91e0154c80b/tlslite/utils/python_dsakey.py#L94)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

shouldn't `self.p` and `self.q` already be mpz's?
</blockquote></details>

I meant in this place here, using gmpy for calculations is fine, I just don't see a reason to cast mpz to mpz
___
*[tlslite/utils/python_dsakey.py, line 76 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_NzIcBzkinJ3i5wDX:-MF_NzIcBzkinJ3i5wDY:bbs1lm0) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/tlslite/utils/python_dsakey.py#L76)):*
> ```Python
>         # get r, s keys
>         body, rest = remove_sequence(signature)
>         assert bytesToNumber(rest) == 0
> ```

asserts are optimised out, we should return False or raise exception here

also, why the `bytesToNumber`? a bytearray has a boolean value, it's False if it's empty, and True if it has at least one byte in it
___
*[tlslite/utils/python_dsakey.py, line 79 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_OLPw5m8kJxyzxTTr:-MF_OLPw5m8kJxyzxTTs:b-2guby3) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/tlslite/utils/python_dsakey.py#L79)):*
> ```Python
>         r, rest = remove_integer(body)
>         s, rest = remove_integer(rest)
>         assert bytesToNumber(rest) == 0
> ```

same here
___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 28 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_P34P8ARMMWCP7DGj:-MF_P34P8ARMMWCP7DGk:b62nx7w) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/unit_tests/test_tlslite_utils_python_dsakey.py#L28)):*
> ```Python
> 
>         # sha1 signature of message 'some message to sign'
>         cls.sha1_sig = \
> ```

I don't see this signature verified anywhere...
___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 71 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_PJ0hCI2R5jQAoSIx:-MF_PJ0hCI2R5jQAoSIy:b-2oug3w) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/unit_tests/test_tlslite_utils_python_dsakey.py#L71)):*
> ```Python
> 
> 
>     def test_verify(self):
> ```

negative test cases missing:
1. signature from different key
2. signatures from different message
3. malformed signatures


<!-- Sent from Reviewable.io -->

2020-08-25 12:15 UTC, tomato42 requested changes
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: all files reviewed, 9 unresolved discussions (waiting on @Stonemason5040)

___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 38 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_XdD6-_US0GBJRUU2:-MF_XdD6-_US0GBJRUU3:b53en7e) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/unit_tests/test_tlslite_utils_python_dsakey.py#L38)):*
> ```Python
>         # TODO: change the bit size from 2048 to smaller?
>         key = (
>             "-----BEGIN DSA PRIVATE KEY-----\n"
> ```

that's the legacy format, we should also test support for PKCS#8 files


<!-- Sent from Reviewable.io -->

2020-08-26 12:48 UTC, tomato42 requested changes
> Reviewed 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: all files reviewed, 6 unresolved discussions (waiting on @Stonemason5040)

*[a discussion](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVExJr5Ojc82zVX1Hc:-MFenxX51jU-RMb4lBry:b-r95pm0) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

You'll need to rebase and drop the Ivan's patch
</blockquote></details>

please rebase on top of master branch

---
___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 28 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_P34P8ARMMWCP7DGj:-MFenPI86DxOREv7lVK8:bafqlef) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/unit_tests/test_tlslite_utils_python_dsakey.py#L28)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I don't see this signature verified anywhere...
</blockquote></details>

I think we should have hardcoded values we check if we can verify; otherwise it's possible to make errors that both create and accept malformed signatures
___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 20 at r9](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFenMf32x-SZEf6HN4a:-MFenMf32x-SZEf6HN4b:b-40zms1) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b465354c44c0c16cf8f9fcbeec90aed6d048fbd9/unit_tests/test_tlslite_utils_python_dsakey.py#L20)):*
> ```Python
>     @classmethod
>     def setUpClass(cls):
>         # TODO: probably change the size for faster testing
> ```

I think we can remove the TODO now
___
*[unit_tests/test_tlslite_x509.py, line 45 at r9](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFen4hqACdn9zanDayM:-MFen4hqACdn9zanDayN:b-jgaky0) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b465354c44c0c16cf8f9fcbeec90aed6d048fbd9/unit_tests/test_tlslite_x509.py#L45)):*
> ```Python
>         self.assertEqual(x509.publicKey.public_key.pubkey.point.y(),
>             12490546948316647166662676770106859255378658810545502161335656899238893361610)
>         self.assertEqual(x509.publicKey.curve_name, "NIST256p")
> ```

wait, what? both `curve_name` and `pubkey.point` are ECDSA specific...


<!-- Sent from Reviewable.io -->

2020-08-28 08:30 UTC, Stonemason5040 reviewed
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @tomato42)

*[a discussion](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVExJr5Ojc82zVX1Hc:-MF_UNv45OuIvsG7n9kW:b-896fix) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

You'll need to rebase and drop the Ivan's patch
</blockquote></details>

Done.

---
___
*[tlslite/x509.py, line 137 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_PiTM0qnB2gH768jY:-MF_UPHpBnnGccLuw0x7:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/tlslite/x509.py#L137)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

`_ecdsa_pubkey_parsing`?
</blockquote></details>

Done.
___
*[tlslite/x509.py, line 198 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_Q6WV6JtQIUxDGuJn:-MFo6K3J-YV4kF3HcY4h:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/tlslite/x509.py#L198)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

test case with a X.509 certificate?
</blockquote></details>

Done.
___
*[tlslite/utils/python_dsakey.py, line 37 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVG6PGD7auLLhM5e4W:-MF_V7dJ5LTaJI3F4k0V:b-21jxno) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf698cb8b4f7e2e095a2bca2fe0af91e0154c80b/tlslite/utils/python_dsakey.py#L37)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

technically, those are the only valid parameters if we want to be FIPS compliant, but for generation it's probably fine to limit to just those
</blockquote></details>

So leave this be ?
___
*[tlslite/utils/python_dsakey.py, line 94 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVJ9TV-lsx_0unBxz4:-MF_VH52B4P2-C6yJm7C:b-nb1k9l) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf698cb8b4f7e2e095a2bca2fe0af91e0154c80b/tlslite/utils/python_dsakey.py#L94)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I meant in this place here, using gmpy for calculations is fine, I just don't see a reason to cast mpz to mpz
</blockquote></details>

I understand, i will implement GMPY after everything is working 
___
*[tlslite/utils/python_dsakey.py, line 76 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_NzIcBzkinJ3i5wDX:-MF_V23S-hypDCyLG_ri:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/tlslite/utils/python_dsakey.py#L76)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

asserts are optimised out, we should return False or raise exception here

also, why the `bytesToNumber`? a bytearray has a boolean value, it's False if it's empty, and True if it has at least one byte in it
</blockquote></details>

Done.
___
*[tlslite/utils/python_dsakey.py, line 79 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_OLPw5m8kJxyzxTTr:-MF_V2ck86i1RWO1zftZ:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/tlslite/utils/python_dsakey.py#L79)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 28 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_P34P8ARMMWCP7DGj:-MFimzI53LK3LxHoEpKo:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/unit_tests/test_tlslite_utils_python_dsakey.py#L28)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I think we should have hardcoded values we check if we can verify; otherwise it's possible to make errors that both create and accept malformed signatures
</blockquote></details>

Done.
___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 71 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_PJ0hCI2R5jQAoSIx:-MFo95Y4Cp7M9mUOwOPz:b9lswsx) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/unit_tests/test_tlslite_utils_python_dsakey.py#L71)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

negative test cases missing:
1. signature from different key
2. signatures from different message
3. malformed signatures
</blockquote></details>

1. a 2. are DONE.
what should i check with the malformed signature?(0 < s < q && 0 <  r < q)?
___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 20 at r9](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFenMf32x-SZEf6HN4a:-MFimxOA4k7za4DilfMo:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b465354c44c0c16cf8f9fcbeec90aed6d048fbd9/unit_tests/test_tlslite_utils_python_dsakey.py#L20)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I think we can remove the TODO now
</blockquote></details>

Done.
___
*[unit_tests/test_tlslite_x509.py, line 45 at r9](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFen4hqACdn9zanDayM:-MFin4f6B--o_IPBvB-S:b-6rdxvw) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b465354c44c0c16cf8f9fcbeec90aed6d048fbd9/unit_tests/test_tlslite_x509.py#L45)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

wait, what? both `curve_name` and `pubkey.point` are ECDSA specific...
</blockquote></details>

Sorry i was just working on it accidentally pushed it.


<!-- Sent from Reviewable.io -->

2020-08-28 12:33 UTC, tomato42 requested changes
> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: all files reviewed, 2 unresolved discussions (waiting on @Stonemason5040)

___
*[tlslite/utils/python_dsakey.py, line 37 at r6](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFVG6PGD7auLLhM5e4W:-MFp-QeQ7kGhmeE3JvqS:b-1lazt4) ([raw file](https://github.com/tomato42/tlslite-ng/blob/cf698cb8b4f7e2e095a2bca2fe0af91e0154c80b/tlslite/utils/python_dsakey.py#L37)):*
<details><summary><i>Previously, Stonemason5040 (Frantisek Krenzelok) wrote…</i></summary><blockquote>

So leave this be ?
</blockquote></details>

yeah, for now it's ok
___
*[tlslite/utils/python_dsakey.py, line 81 at r10](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFp220j7xCGvi3RDwup:-MFp220k789ksQl3eWoR:b-ddu1hx) ([raw file](https://github.com/tomato42/tlslite-ng/blob/ee3163d1a132cd904991f5a4238cb9a2b4e54d70/tlslite/utils/python_dsakey.py#L81)):*
> ```Python
>         # get r, s keys
>         if not signature:
>             raise ValueError("Empty dsa signature")
> ```

I've looked how malformed ecdsa and rsa signatures are handled and they don't raise exceptions, they just return `False`, I think it will be better for API compatibility to do the same here (and in the two instances below)
___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 71 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_PJ0hCI2R5jQAoSIx:-MFp0ICh2D9ResTF7rHy:ba77r2v) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/unit_tests/test_tlslite_utils_python_dsakey.py#L71)):*
<details><summary><i>Previously, Stonemason5040 (Frantisek Krenzelok) wrote…</i></summary><blockquote>

1. a 2. are DONE.
what should i check with the malformed signature?(0 < s < q && 0 <  r < q)?
</blockquote></details>

you can create one with the same `encode_sequence(encode_integer())` as in hashAndSign, take a correct s, add q to it, see if it is rejected, same for r

same for creating a signature with more than 2 elements in the sequence, just do a `encode_sequence(encode_integer(r), encode_integer(s), encode_integer(0))` and for garbage after sequence a simple `sig += b'\x00'` should be enough


<!-- Sent from Reviewable.io -->

2020-08-28 14:20 UTC, Stonemason5040 reviewed
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @tomato42)

___
*[tlslite/utils/python_dsakey.py, line 81 at r10](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFp220j7xCGvi3RDwup:-MFpRAaI0ZXfpkcydF5H:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/ee3163d1a132cd904991f5a4238cb9a2b4e54d70/tlslite/utils/python_dsakey.py#L81)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I've looked how malformed ecdsa and rsa signatures are handled and they don't raise exceptions, they just return `False`, I think it will be better for API compatibility to do the same here (and in the two instances below)
</blockquote></details>

Done.
___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 71 at r8](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MF_PJ0hCI2R5jQAoSIx:-MFpRCwhDmHzl_utD8jL:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/b06fd3355ec451c47e7aa16b1b327275b5b43a2d/unit_tests/test_tlslite_utils_python_dsakey.py#L71)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

you can create one with the same `encode_sequence(encode_integer())` as in hashAndSign, take a correct s, add q to it, see if it is rejected, same for r

same for creating a signature with more than 2 elements in the sequence, just do a `encode_sequence(encode_integer(r), encode_integer(s), encode_integer(0))` and for garbage after sequence a simple `sig += b'\x00'` should be enough
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-28 17:54 UTC, tomato42 requested changes
`unit_tests.test_tlslite_x509.Test_DSA_X509.test_pem` fails in Travis...

> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-:-MFqC4113ijnbfBKaM0T:b-4u3kxg)* status: all files reviewed, 2 unresolved discussions (waiting on @Stonemason5040 and @tomato42)

___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 96 at r11](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFqBh4M0fMGR-QlbQaB:-MFqBh4M0fMGR-QlbQaC:b4av2x0) ([raw file](https://github.com/tomato42/tlslite-ng/blob/eab7830225f68a024fe00a9956d791867c523959/unit_tests/test_tlslite_utils_python_dsakey.py#L96)):*
> ```Python
>                 b'\xab\x1c\x69\x89\x45\xdf\x67\xa4\x47')
> 
>         self.assertFalse(self.key_diff.hashAndVerify(sig, msg))
> ```

please, one test per method, otherwise when first assert fails other failures won't be visible until the first one is fixed


<!-- Sent from Reviewable.io -->

2020-09-03 14:23 UTC, Stonemason5040 commented
___
*[unit_tests/test_tlslite_utils_python_dsakey.py, line 96 at r11](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MFqBh4M0fMGR-QlbQaB:-MGJLPi2D9rD_qaK41uD:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/eab7830225f68a024fe00a9956d791867c523959/unit_tests/test_tlslite_utils_python_dsakey.py#L96)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

please, one test per method, otherwise when first assert fails other failures won't be visible until the first one is fixed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-03 14:59 UTC, tomato42 requested changes
> Reviewed 11 of 11 files at r13.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: all files reviewed, 4 unresolved discussions (waiting on @Stonemason5040)

___
*[tlslite/constants.py, line 241 at r13](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MGJTMzx1VuFfL5xWrTj:-MGJTMzy9LgBd6v9iaXH:b-a18nke) ([raw file](https://github.com/tomato42/tlslite-ng/blob/9e70455db3c997254ba87992302ec8937f713ea3/tlslite/constants.py#L241)):*
> ```Python
> 
>     dsa_sha1 = (2, 2)
>     dsa_sha256 = (4, 2)
> ```

why no `dsa_sha224`?
___
*[tlslite/constants.py, line 243 at r13](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MGJRGKX7LWlvzXW4FNL:-MGJRGKYBPyYe5_iRWIv:b-a0xyfd) ([raw file](https://github.com/tomato42/tlslite-ng/blob/9e70455db3c997254ba87992302ec8937f713ea3/tlslite/constants.py#L243)):*
> ```Python
>     dsa_sha256 = (4, 2)
>     dsa_sha384 = (5, 2)
>     dsa_sha_512 = (6, 2)
> ```

why the different format for SHA-512?
___
*[tlslite/constants.py, line 348 at r13](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MGJTXDNAZTxJbaMlNIb:-MGJTXDNAZTxJbaMlNIc:bmf1cbp) ([raw file](https://github.com/tomato42/tlslite-ng/blob/9e70455db3c997254ba87992302ec8937f713ea3/tlslite/constants.py#L348)):*
> ```Python
>             SignatureScheme.dsa_sha1
>     oid[bytes(a2b_hex('0609608648016503040302'))] = \
>             SignatureScheme.dsa_sha256
> ```

why no OID for `dsa_sha224`?
___
*[tlslite/constants.py, line 352 at r13](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MGJTUFN-TWXhSccLuIx:-MGJTUFN-TWXhSccLuIy:b-ldhpz7) ([raw file](https://github.com/tomato42/tlslite-ng/blob/9e70455db3c997254ba87992302ec8937f713ea3/tlslite/constants.py#L352)):*
> ```Python
>             SignatureScheme.dsa_sha384
>     oid[bytes(a2b_hex('0609608648016503040304'))] = \
>             SignatureScheme.dsa_sha_512
> ```

this will need change too


<!-- Sent from Reviewable.io -->

2020-09-07 08:44 UTC, Stonemason5040 reviewed
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @Stonemason5040 and @tomato42)

___
*[tlslite/constants.py, line 241 at r13](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MGJTMzx1VuFfL5xWrTj:-MGbgk9uEs_H5hslnkIC:b-ltalvl) ([raw file](https://github.com/tomato42/tlslite-ng/blob/9e70455db3c997254ba87992302ec8937f713ea3/tlslite/constants.py#L241)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why no `dsa_sha224`?
</blockquote></details>

I have not found any more references to SignatureSchemeList other than RFC 8446 and it was not mentioned here, could you direct me to a better source
___
*[tlslite/constants.py, line 243 at r13](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MGJRGKX7LWlvzXW4FNL:-MGbihdw4xT9e0lb0GvA:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/9e70455db3c997254ba87992302ec8937f713ea3/tlslite/constants.py#L243)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why the different format for SHA-512?
</blockquote></details>

Done.
___
*[tlslite/constants.py, line 352 at r13](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MGJTUFN-TWXhSccLuIx:-MGbj3ud2UTM8akJ3-Z8:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/9e70455db3c997254ba87992302ec8937f713ea3/tlslite/constants.py#L352)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

this will need change too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-07 13:20 UTC, tomato42 requested changes
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: all files reviewed, 2 unresolved discussions (waiting on @Stonemason5040)

___
*[tlslite/constants.py, line 241 at r13](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MGJTMzx1VuFfL5xWrTj:-MGchAKC6Eh3S5k1ub0s:b-tkfjf8) ([raw file](https://github.com/tomato42/tlslite-ng/blob/9e70455db3c997254ba87992302ec8937f713ea3/tlslite/constants.py#L241)):*
<details><summary><i>Previously, Stonemason5040 (Frantisek Krenzelok) wrote…</i></summary><blockquote>

I have not found any more references to SignatureSchemeList other than RFC 8446 and it was not mentioned here, could you direct me to a better source
</blockquote></details>

well, technically speaking, SignatureScheme reflects the IANA SignatureScheme: https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-signaturescheme so there are no dsa signatures there at all, but in practice it's just a concatenation of HashAlgorithm and SignatureAlgorithm, and this is defined in https://tools.ietf.org/html/rfc5246 where used hashes with DSA are not limited


<!-- Sent from Reviewable.io -->

2020-09-08 07:37 UTC, Stonemason5040 reviewed
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @tomato42)

___
*[tlslite/constants.py, line 241 at r13](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MGJTMzx1VuFfL5xWrTj:-MGgdYSPDruijCyN78kb:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/9e70455db3c997254ba87992302ec8937f713ea3/tlslite/constants.py#L241)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

well, technically speaking, SignatureScheme reflects the IANA SignatureScheme: https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-signaturescheme so there are no dsa signatures there at all, but in practice it's just a concatenation of HashAlgorithm and SignatureAlgorithm, and this is defined in https://tools.ietf.org/html/rfc5246 where used hashes with DSA are not limited
</blockquote></details>

Done.
___
*[tlslite/constants.py, line 348 at r13](https://reviewable.io/reviews/tomato42/tlslite-ng/418#-MGJTXDNAZTxJbaMlNIb:-MGgdWIg3e77UP-PnOqF:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/9e70455db3c997254ba87992302ec8937f713ea3/tlslite/constants.py#L348)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why no OID for `dsa_sha224`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-08 11:00 UTC, tomato42 approved these changes
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/418)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-08 11:01 UTC, tomato42 commented
looks good, thanks!

2020-09-08 11:01 UTC, merged